### ISSUE TITLE
Problem with RecyclerView

### ISSUE THREAD

**Issue by sjuniorvc89** [tiagohs/PopMovies#2]
br.com.tiagohs.popmovies E/RecyclerView: No adapter attached; skipping layout

**Comment by tiagohs** [comment]
Onde está acontecendo essa exception ? Em qual classe ?

**Comment by sjuniorvc89** [comment]
as can i see, it is on moviedetails, when you want to enter on any movie you get that error.

**Comment by tiagohs** [comment]
O Problema estão nas Classes MediaCreditCast e MediaCreditCrew, aparentemente o TheMovieDB adicionou mais um atributo no JSON de retorno.. adicione: 
`@JsonProperty("gender")
    private string gender;`

nas duas classes, com seus gets e sets, que deve voltar ao normal. Irei atualizar hoje ou amanhã o github. Obrigado por avisar e qualquer outra problema, é só avisar!
